In [1]:
print("Hello, Hospital Analytics!")

Hello, Hospital Analytics!

In [2]:
import sqlite3

connection = sqlite3.connect("Hospital-Operations-Analytics.db")

print(connection)

<sqlite3.Connection object at 0x1090b0d60>

In [3]:
import pandas as pd

doctors_df = pd.read_sql_query(
    "SELECT * FROM doctors;",
    connection
)

doctors_df

DatabaseError: Execution failed on sql 'SELECT * FROM doctors;': no such table: doctors

In [4]:
tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", connection)

tables

Empty DataFrame
Columns: [name]
Index: []

In [5]:
tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", connection)

print(tables)

Empty DataFrame
Columns: [name]
Index: []

In [6]:
import pandas as pd

pd.read_sql_query(
    "SELECT name FROM sqlite_master;",
    connection
)

Empty DataFrame
Columns: [name]
Index: []

In [7]:
import os

print(os.path.abspath("Hospital-Operations-Analytics.db"))

/Users/akshitajoshi/Hospital-Operations-Analytics.db

In [8]:
import sqlite3

connection = sqlite3.connect(
    "/Users/akshitajoshi/Hospital_Data_Analytics_Internship/Hospital-Operations-Analytics.db"
)

print(connection)

<sqlite3.Connection object at 0x10be09a80>

In [9]:
import pandas as pd

tables = pd.read_sql_query("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", connection)

tables

            name
0    departments
1       patients
2        doctors
3   appointments
4     encounters
5        billing
6       payments
7  prescriptions

In [10]:
import pandas as pd

doctors_df = pd.read_sql_query("""
SELECT *
FROM doctors;
""", connection)

doctors_df.head()

,doctor_id,first_name,last_name,specialization,phone,email,department_id,experience_years
0,1,Arjun,Mehta,Cardiologist,9000000001,arjun@hospital.com,1,12
1,2,Neha,Kapoor,Cardiologist,9000000002,neha@hospital.com,1,8
2,3,Rohan,Iyer,Neurologist,9000000003,rohan@hospital.com,2,10
3,4,Priya,Nair,Neurologist,9000000004,priya@hospital.com,2,6
4,5,Vikram,Singh,Orthopedic,9000000005,vikram@hospital.com,3,11

In [11]:
doctors_df.tail()

,doctor_id,first_name,last_name,specialization,phone,email,department_id,experience_years
5,6,Aisha,Verma,Orthopedic,9000000006,aisha@hospital.com,3,5
6,7,Karan,Shah,Pediatrician,9000000007,karan@hospital.com,4,9
7,8,Sana,Ali,Emergency,9000000008,sana@hospital.com,5,7
8,9,Rahul,Joshi,Emergency,9000000009,rahul@hospital.com,5,4
9,10,Meera,Patel,Emergency,9000000010,meera@hospital.com,5,13

In [12]:
doctors_df.columns

Index(['doctor_id', 'first_name', 'last_name', 'specialization', 'phone',
       'email', 'department_id', 'experience_years'],
      dtype='str')

In [13]:
doctors_df.shape

(10, 8)

In [14]:
doctors_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     int64
 1   first_name        10 non-null     str
 2   last_name         10 non-null     str
 3   specialization    10 non-null     str
 4   phone             10 non-null     str
 5   email             10 non-null     str
 6   department_id     10 non-null     int64
 7   experience_years  10 non-null     int64
dtypes: int64(3), str(5)
memory usage: 772.0 bytes

In [15]:
doctors_df.describe()

       doctor_id  department_id  experience_years
count   10.00000      10.000000          10.00000
mean     5.50000       3.100000           8.50000
std      3.02765       1.595131           3.02765
min      1.00000       1.000000           4.00000
25%      3.25000       2.000000           6.25000
50%      5.50000       3.000000           8.50000
75%      7.75000       4.750000          10.75000
max     10.00000       5.000000          13.00000

In [16]:
doctors_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     int64
 1   first_name        10 non-null     str
 2   last_name         10 non-null     str
 3   specialization    10 non-null     str
 4   phone             10 non-null     str
 5   email             10 non-null     str
 6   department_id     10 non-null     int64
 7   experience_years  10 non-null     int64
dtypes: int64(3), str(5)
memory usage: 772.0 bytes

In [17]:
doctors_df[["first_name", "last_name"]]

  first_name last_name
0      Arjun     Mehta
1       Neha    Kapoor
2      Rohan      Iyer
3      Priya      Nair
4     Vikram     Singh
5      Aisha     Verma
6      Karan      Shah
7       Sana       Ali
8      Rahul     Joshi
9      Meera     Patel

In [18]:
doctors_df.dtypes

doctor_id           int64
first_name            str
last_name             str
specialization        str
phone                 str
email                 str
department_id       int64
experience_years    int64
dtype: object

In [19]:
doctors_df.isnull().sum()

doctor_id           0
first_name          0
last_name           0
specialization      0
phone               0
email               0
department_id       0
experience_years    0
dtype: int64

In [20]:
doctors_df["first_name"]

0     Arjun
1      Neha
2     Rohan
3     Priya
4    Vikram
5     Aisha
6     Karan
7      Sana
8     Rahul
9     Meera
Name: first_name, dtype: str

In [21]:
doctors_df[
    [
        "first_name",
        "last_name",
        "specialization"
    ]
]

  first_name last_name specialization
0      Arjun     Mehta   Cardiologist
1       Neha    Kapoor   Cardiologist
2      Rohan      Iyer    Neurologist
3      Priya      Nair    Neurologist
4     Vikram     Singh     Orthopedic
5      Aisha     Verma     Orthopedic
6      Karan      Shah   Pediatrician
7       Sana       Ali      Emergency
8      Rahul     Joshi      Emergency
9      Meera     Patel      Emergency

In [22]:
doctors_df[
    doctors_df["experience_years"] > 10
]

,doctor_id,first_name,last_name,specialization,phone,email,department_id,experience_years
0,1,Arjun,Mehta,Cardiologist,9000000001,arjun@hospital.com,1,12
4,5,Vikram,Singh,Orthopedic,9000000005,vikram@hospital.com,3,11
9,10,Meera,Patel,Emergency,9000000010,meera@hospital.com,5,13

In [23]:
doctors_df[
    (doctors_df["specialization"] == "Cardiology") &
    (doctors_df["experience_years"] > 8)
]

Empty DataFrame
Columns: [doctor_id, first_name, last_name, specialization, phone, email, department_id, experience_years]
Index: []

In [24]:
doctors_df[
    (doctors_df["specialization"] == "Cardiology") |
    (doctors_df["specialization"] == "Neurology")
]

Empty DataFrame
Columns: [doctor_id, first_name, last_name, specialization, phone, email, department_id, experience_years]
Index: []

In [25]:
doctors_df.sort_values(
    by="experience_years",
    ascending=False
)

,doctor_id,first_name,last_name,specialization,phone,email,department_id,experience_years
9,10,Meera,Patel,Emergency,9000000010,meera@hospital.com,5,13
0,1,Arjun,Mehta,Cardiologist,9000000001,arjun@hospital.com,1,12
4,5,Vikram,Singh,Orthopedic,9000000005,vikram@hospital.com,3,11
2,3,Rohan,Iyer,Neurologist,9000000003,rohan@hospital.com,2,10
6,7,Karan,Shah,Pediatrician,9000000007,karan@hospital.com,4,9
1,2,Neha,Kapoor,Cardiologist,9000000002,neha@hospital.com,1,8
7,8,Sana,Ali,Emergency,9000000008,sana@hospital.com,5,7
3,4,Priya,Nair,Neurologist,9000000004,priya@hospital.com,2,6
5,6,Aisha,Verma,Orthopedic,9000000006,aisha@hospital.com,3,5
8,9,Rahul,Joshi,Emergency,9000000009,rahul@hospital.com,5,4

In [26]:
(
    doctors_df[doctors_df["experience_years"] > 10]
    [["first_name", "last_name", "experience_years"]]
    .sort_values(by="experience_years", ascending=False)
)

  first_name last_name  experience_years
9      Meera     Patel                13
0      Arjun     Mehta                12
4     Vikram     Singh                11

In [27]:
doctors_df.duplicated().sum()

np.int64(0)

In [28]:
doctors_df.dtypes

doctor_id           int64
first_name            str
last_name             str
specialization        str
phone                 str
email                 str
department_id       int64
experience_years    int64
dtype: object

In [29]:
doctors_df.groupby("department_id")["experience_years"].mean()

department_id
1    10.0
2     8.0
3     8.0
4     9.0
5     8.0
Name: experience_years, dtype: float64

In [30]:
doctors_df.groupby("department_id")["doctor_id"].count()

department_id
1    2
2    2
3    2
4    1
5    3
Name: doctor_id, dtype: int64

In [31]:
doctors_df.groupby("department_id")["experience_years"].max()

department_id
1    12
2    10
3    11
4     9
5    13
Name: experience_years, dtype: int64

In [33]:
doctors_df["experience_level"] = doctors_df["experience_years"].apply(
    lambda x: "Junior" if x < 5 else
              "Mid-Level" if x < 10 else
              "Senior"
)

In [2]:
import numpy as np
import pandas as pd
import sqlite3

In [3]:
connection = sqlite3.connect(
    "/Users/akshitajoshi/Hospital_Data_Analytics_Internship/Hospital-Operations-Analytics.db"
)

In [4]:
patients_df = pd.read_sql_query("SELECT * FROM patients;", connection)

doctors_df = pd.read_sql_query("SELECT * FROM doctors;", connection)

departments_df = pd.read_sql_query("SELECT * FROM departments;", connection)

appointments_df = pd.read_sql_query("SELECT * FROM appointments;", connection)

encounters_df = pd.read_sql_query("SELECT * FROM encounters;", connection)

billing_df = pd.read_sql_query("SELECT * FROM billing;", connection)

payments_df = pd.read_sql_query("SELECT * FROM payments;", connection)

prescriptions_df = pd.read_sql_query("SELECT * FROM prescriptions;", connection)

In [6]:
# Hospital Operations Analytics

## Exploratory Data Analysis (EDA)

### Objective To understand the structure, quality, and characteristics of the hospital database by generating summary statistics and identifying key business insights using Python, Pandas, and NumPy.

In [7]:
print("=" * 50)
print("Doctors Table Overview")
print("=" * 50)

print(f"Rows: {doctors_df.shape[0]}")
print(f"Columns: {doctors_df.shape[1]}")

print("\nColumn Names:")
print(doctors_df.columns.tolist())

==================================================
Doctors Table Overview
==================================================
Rows: 10
Columns: 8

Column Names:
['doctor_id', 'first_name', 'last_name', 'specialization', 'phone', 'email', 'department_id', 'experience_years']

In [8]:
doctors_df.describe()

       doctor_id  department_id  experience_years
count   10.00000      10.000000          10.00000
mean     5.50000       3.100000           8.50000
std      3.02765       1.595131           3.02765
min      1.00000       1.000000           4.00000
25%      3.25000       2.000000           6.25000
50%      5.50000       3.000000           8.50000
75%      7.75000       4.750000          10.75000
max     10.00000       5.000000          13.00000

In [9]:
experience = doctors_df["experience_years"]

print("Mean:", np.mean(experience))
print("Median:", np.median(experience))
print("Minimum:", np.min(experience))
print("Maximum:", np.max(experience))
print("Standard Deviation:", np.std(experience))

Mean: 8.5
Median: 8.5
Minimum: 4
Maximum: 13
Standard Deviation: 2.8722813232690143

In [10]:
def perform_eda(df,table_name):
    print("=" * 50)
    print(f"EDA Report: {table_name}")
    print("=" * 50)

    print("\nShape:")
    print(df.shape)
    
    print("\nColumns:")
    print(df.columns.tolist())
    
    print("\nData Types")
    print(df.dtypes)
    
    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nSummary Statistics:")
    print(df.describe(include='all'))

    print("\n")

In [11]:
perform_eda(patients_df,"Patients")

==================================================
EDA Report: Patients
==================================================

Shape:
(30, 10)

Columns:
['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'phone', 'email', 'address', 'blood_group', 'registration_date']

Data Types
patient_id           int64
first_name             str
last_name              str
gender                 str
date_of_birth          str
phone                  str
email                  str
address                str
blood_group            str
registration_date      str
dtype: object

Missing Values:
patient_id           0
first_name           0
last_name            0
gender               0
date_of_birth        0
phone                0
email                0
address              0
blood_group          0
registration_date    0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        patient_id first_name last_name gender date_of_birth       phone  \
count    30.000000         30        30     30            30          30
unique         NaN         30         1      2            10          30
top            NaN   Patient1      Test   Male    1981-01-15  9800000001
freq           NaN          1        30     15             3           1
mean     15.500000        NaN       NaN    NaN           NaN         NaN
std       8.803408        NaN       NaN    NaN           NaN         NaN
min       1.000000        NaN       NaN    NaN           NaN         NaN
25%       8.250000        NaN       NaN    NaN           NaN         NaN
50%      15.500000        NaN       NaN    NaN           NaN         NaN
75%      22.750000        NaN       NaN    NaN           NaN         NaN
max      30.000000        NaN       NaN    NaN           NaN         NaN

                    email address blood_group registration_date
count                  30      30          30                30
unique                 30      30           1                28
top     patient1@mail.com  City 1          O+        2026-06-02
freq                    1       1          30                 2
mean                  NaN     NaN         NaN               NaN
std                   NaN     NaN         NaN               NaN
min                   NaN     NaN         NaN               NaN
25%                   NaN     NaN         NaN               NaN
50%                   NaN     NaN         NaN               NaN
75%                   NaN     NaN         NaN               NaN
max                   NaN     NaN         NaN               NaN

In [12]:
perform_eda(doctors_df,"Doctors")

==================================================
EDA Report: Doctors
==================================================

Shape:
(10, 8)

Columns:
['doctor_id', 'first_name', 'last_name', 'specialization', 'phone', 'email', 'department_id', 'experience_years']

Data Types
doctor_id           int64
first_name            str
last_name             str
specialization        str
phone                 str
email                 str
department_id       int64
experience_years    int64
dtype: object

Missing Values:
doctor_id           0
first_name          0
last_name           0
specialization      0
phone               0
email               0
department_id       0
experience_years    0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        doctor_id first_name last_name specialization       phone  \
count    10.00000         10        10             10          10
unique        NaN         10        10              5          10
top           NaN      Arjun     Mehta      Emergency  9000000001
freq          NaN          1         1              3           1
mean      5.50000        NaN       NaN            NaN         NaN
std       3.02765        NaN       NaN            NaN         NaN
min       1.00000        NaN       NaN            NaN         NaN
25%       3.25000        NaN       NaN            NaN         NaN
50%       5.50000        NaN       NaN            NaN         NaN
75%       7.75000        NaN       NaN            NaN         NaN
max      10.00000        NaN       NaN            NaN         NaN

                     email  department_id  experience_years
count                   10      10.000000          10.00000
unique                  10            NaN               NaN
top     arjun@hospital.com            NaN               NaN
freq                     1            NaN               NaN
mean                   NaN       3.100000           8.50000
std                    NaN       1.595131           3.02765
min                    NaN       1.000000           4.00000
25%                    NaN       2.000000           6.25000
50%                    NaN       3.000000           8.50000
75%                    NaN       4.750000          10.75000
max                    NaN       5.000000          13.00000

In [13]:
perform_eda(departments_df,"Departments")

==================================================
EDA Report: Departments
==================================================

Shape:
(5, 4)

Columns:
['department_id', 'department_name', 'location', 'head_of_department']

Data Types
department_id          int64
department_name          str
location                 str
head_of_department    object
dtype: object

Missing Values:
department_id         0
department_name       0
location              0
head_of_department    5
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        department_id department_name           location head_of_department
count        5.000000               5                  5                  0
unique            NaN               5                  5                  0
top               NaN      Cardiology  Block A - Floor 2                NaN
freq              NaN               1                  1                NaN
mean         3.000000             NaN                NaN                NaN
std          1.581139             NaN                NaN                NaN
min          1.000000             NaN                NaN                NaN
25%          2.000000             NaN                NaN                NaN
50%          3.000000             NaN                NaN                NaN
75%          4.000000             NaN                NaN                NaN
max          5.000000             NaN                NaN                NaN

In [14]:
perform_eda(appointments_df,"Appointments")

==================================================
EDA Report: Appointments
==================================================

Shape:
(50, 6)

Columns:
['appointment_id', 'patient_id', 'doctor_id', 'appointment_date', 'appointment_time', 'appointment_status']

Data Types
appointment_id        int64
patient_id            int64
doctor_id             int64
appointment_date        str
appointment_time        str
appointment_status      str
dtype: object

Missing Values:
appointment_id        0
patient_id            0
doctor_id             0
appointment_date      0
appointment_time      0
appointment_status    0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        appointment_id  patient_id  doctor_id appointment_date  \
count         50.00000   50.000000  50.000000               50
unique             NaN         NaN        NaN               28
top                NaN         NaN        NaN       2026-07-01
freq               NaN         NaN        NaN                2
mean          25.50000   13.500000   5.500000              NaN
std           14.57738    8.096989   2.901442              NaN
min            1.00000    1.000000   1.000000              NaN
25%           13.25000    7.000000   3.000000              NaN
50%           25.50000   13.000000   5.500000              NaN
75%           37.75000   19.000000   8.000000              NaN
max           50.00000   30.000000  10.000000              NaN

       appointment_time appointment_status
count                50                 50
unique                1                  4
top               09:00          Completed
freq                 50                 35
mean                NaN                NaN
std                 NaN                NaN
min                 NaN                NaN
25%                 NaN                NaN
50%                 NaN                NaN
75%                 NaN                NaN
max                 NaN                NaN

In [15]:
perform_eda(encounters_df,"Encounters")

==================================================
EDA Report: Encounters
==================================================

Shape:
(35, 5)

Columns:
['encounter_id', 'appointment_id', 'diagnosis', 'consultation_notes', 'consultation_duration']

Data Types
encounter_id             int64
appointment_id           int64
diagnosis                  str
consultation_notes         str
consultation_duration    int64
dtype: object

Missing Values:
encounter_id             0
appointment_id           0
diagnosis                0
consultation_notes       0
consultation_duration    0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        encounter_id  appointment_id    diagnosis consultation_notes  \
count      35.000000       35.000000           35                 35
unique           NaN             NaN           35                  1
top              NaN             NaN  Diagnosis 1             Stable
freq             NaN             NaN            1                 35
mean       18.000000       18.000000          NaN                NaN
std        10.246951       10.246951          NaN                NaN
min         1.000000        1.000000          NaN                NaN
25%         9.500000        9.500000          NaN                NaN
50%        18.000000       18.000000          NaN                NaN
75%        26.500000       26.500000          NaN                NaN
max        35.000000       35.000000          NaN                NaN

        consultation_duration
count               35.000000
unique                    NaN
top                       NaN
freq                      NaN
mean                21.428571
std                  4.333764
min                 15.000000
25%                 18.000000
50%                 21.000000
75%                 25.000000
max                 29.000000

In [16]:
perform_eda(billing_df,"Billing")

==================================================
EDA Report: Billing
==================================================

Shape:
(35, 4)

Columns:
['bill_id', 'encounter_id', 'total_amount', 'billing_date']

Data Types
bill_id         int64
encounter_id    int64
total_amount    int64
billing_date      str
dtype: object

Missing Values:
bill_id         0
encounter_id    0
total_amount    0
billing_date    0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
          bill_id  encounter_id  total_amount billing_date
count   35.000000     35.000000     35.000000           35
unique        NaN           NaN           NaN           28
top           NaN           NaN           NaN   2026-07-01
freq          NaN           NaN           NaN            2
mean    18.000000     18.000000   4000.000000          NaN
std     10.246951     10.246951   1434.860108          NaN
min      1.000000      1.000000   2000.000000          NaN
25%      9.500000      9.500000   3000.000000          NaN
50%     18.000000     18.000000   4000.000000          NaN
75%     26.500000     26.500000   5000.000000          NaN
max     35.000000     35.000000   6000.000000          NaN

In [17]:
perform_eda(payments_df,"Payments")

==================================================
EDA Report: Payments
==================================================

Shape:
(35, 6)

Columns:
['payment_id', 'bill_id', 'payment_method', 'payment_status', 'payment_date', 'amount_paid']

Data Types
payment_id        int64
bill_id           int64
payment_method      str
payment_status      str
payment_date        str
amount_paid       int64
dtype: object

Missing Values:
payment_id        0
bill_id           0
payment_method    0
payment_status    0
payment_date      0
amount_paid       0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        payment_id    bill_id payment_method payment_status payment_date  \
count    35.000000  35.000000             35             35           35
unique         NaN        NaN              4              2           28
top            NaN        NaN           Cash           Paid   2026-07-01
freq           NaN        NaN              9             32            2
mean     18.000000  18.000000            NaN            NaN          NaN
std      10.246951  10.246951            NaN            NaN          NaN
min       1.000000   1.000000            NaN            NaN          NaN
25%       9.500000   9.500000            NaN            NaN          NaN
50%      18.000000  18.000000            NaN            NaN          NaN
75%      26.500000  26.500000            NaN            NaN          NaN
max      35.000000  35.000000            NaN            NaN          NaN

        amount_paid
count     35.000000
unique          NaN
top             NaN
freq            NaN
mean    3828.571429
std     1757.098449
min        0.000000
25%     3000.000000
50%     4000.000000
75%     5000.000000
max     6000.000000

In [18]:
perform_eda(prescriptions_df,"Prescriptions")

==================================================
EDA Report: Prescriptions
==================================================

Shape:
(60, 5)

Columns:
['prescription_id', 'encounter_id', 'medicine_name', 'dosage', 'duration_days']

Data Types
prescription_id    int64
encounter_id       int64
medicine_name        str
dosage               str
duration_days      int64
dtype: object

Missing Values:
prescription_id    0
encounter_id       0
medicine_name      0
dosage             0
duration_days      0
dtype: int64

Duplicate Rows:
0

Summary Statistics:
        prescription_id  encounter_id medicine_name                dosage  \
count         60.000000     60.000000            60                    60
unique              NaN           NaN            60                     1
top                 NaN           NaN    Medicine 1  1 tablet twice daily
freq                NaN           NaN             1                    60
mean          30.500000     15.916667           NaN                   NaN
std           17.464249      9.419222           NaN                   NaN
min            1.000000      1.000000           NaN                   NaN
25%           15.750000      8.000000           NaN                   NaN
50%           30.500000     15.500000           NaN                   NaN
75%           45.250000     23.000000           NaN                   NaN
max           60.000000     35.000000           NaN                   NaN

        duration_days
count            60.0
unique            NaN
top               NaN
freq              NaN
mean              7.0
std               0.0
min               7.0
25%               7.0
50%               7.0
75%               7.0
max               7.0

In [21]:
import pandas as pd
import numpy as np
age = patients_df["age"]
print("Mean:",np.mean(age))
print("Median:",np.median(age))
print("Minimum:",np.min(age))
print("Maximum:",np.max(age))
print("Standard Deviation:",np.std(age))

KeyError: 'age'

In [22]:
print(patients_df.columns.tolist())

['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'phone', 'email', 'address', 'blood_group', 'registration_date']

In [23]:
print("Doctors")
print(doctors_df.columns.tolist())
print("Departments")
print(departments_df.columns.tolist())
print("Appointments")
print(appointments_df.columns.tolist())
print("Encounters")
print(encounters_df.columns.tolist())
print("Billing")
print(billing_df.columns.tolist())
print("Payments")
print(payments_df.columns.tolist())
print("Prescriptions")
print(prescriptions_df.columns.tolist())

Doctors
['doctor_id', 'first_name', 'last_name', 'specialization', 'phone', 'email', 'department_id', 'experience_years']
Departments
['department_id', 'department_name', 'location', 'head_of_department']
Appointments
['appointment_id', 'patient_id', 'doctor_id', 'appointment_date', 'appointment_time', 'appointment_status']
Encounters
['encounter_id', 'appointment_id', 'diagnosis', 'consultation_notes', 'consultation_duration']
Billing
['bill_id', 'encounter_id', 'total_amount', 'billing_date']
Payments
['payment_id', 'bill_id', 'payment_method', 'payment_status', 'payment_date', 'amount_paid']
Prescriptions
['prescription_id', 'encounter_id', 'medicine_name', 'dosage', 'duration_days']

In [24]:
import numpy as np

def perform_eda(df, table_name, numeric_columns=None, categorical_columns=None):

    print("=" * 70)
    print(f"EDA REPORT : {table_name.upper()}")
    print("=" * 70)

    # Dataset Overview
    print("\n📌 Shape")
    print(df.shape)

    print("\n📌 Columns")
    print(df.columns.tolist())

    print("\n📌 Data Types")
    print(df.dtypes)

    # Data Quality
    print("\n📌 Missing Values")
    print(df.isnull().sum())

    print("\n📌 Duplicate Rows")
    print(df.duplicated().sum())

    # Summary Statistics
    print("\n📌 Summary Statistics")
    print(df.describe(include="all"))

    # NumPy Statistics
    if numeric_columns:

        print("\n📌 NumPy Statistics")

        for column in numeric_columns:

            print(f"\n{column}")

            print("Mean:", np.mean(df[column]))
            print("Median:", np.median(df[column]))
            print("Minimum:", np.min(df[column]))
            print("Maximum:", np.max(df[column]))
            print("Standard Deviation:", np.std(df[column]))

    # Frequency Analysis
    if categorical_columns:

        print("\n📌 Frequency Analysis")

        for column in categorical_columns:

            print(f"\n{column}")

            print(df[column].value_counts())

    print("\n" + "=" * 70)

In [25]:
perform_eda(
    doctors_df,
    "Doctors",
    numeric_columns=["experience_years"],
    categorical_columns=["specialization"]
)
perform_eda(
    patients_df,
    "Patients",
    categorical_columns=[
        "gender",
        "blood_group"
    ]
)
perform_eda(
    departments_df,
    "Departments",
    categorical_columns=[
        "department_name",
        "location"
    ]
)

perform_eda(
    appointments_df,
    "Appointments",
    categorical_columns=[
        "appointment_status"
    ]
)

perform_eda(
    encounters_df,
    "Encounters",
    numeric_columns=[
        "consultation_duration"
    ]
)
perform_eda(
    billing_df,
    "Billing",
    numeric_columns=[
        "total_amount"
    ]
)

perform_eda(
    payments_df,
    "Payments",
    numeric_columns=[
        "amount_paid"
    ],
    categorical_columns=[
        "payment_method",
        "payment_status"
    ]
)

perform_eda(
    prescriptions_df,
    "Prescriptions",
    numeric_columns=[
        "duration_days"
    ],
    categorical_columns=[
        "medicine_name"
    ]
)

======================================================================
EDA REPORT : DOCTORS
======================================================================

📌 Shape
(10, 8)

📌 Columns
['doctor_id', 'first_name', 'last_name', 'specialization', 'phone', 'email', 'department_id', 'experience_years']

📌 Data Types
doctor_id           int64
first_name            str
last_name             str
specialization        str
phone                 str
email                 str
department_id       int64
experience_years    int64
dtype: object

📌 Missing Values
doctor_id           0
first_name          0
last_name           0
specialization      0
phone               0
email               0
department_id       0
experience_years    0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        doctor_id first_name last_name specialization       phone  \
count    10.00000         10        10             10          10
unique        NaN         10        10              5          10
top           NaN      Arjun     Mehta      Emergency  9000000001
freq          NaN          1         1              3           1
mean      5.50000        NaN       NaN            NaN         NaN
std       3.02765        NaN       NaN            NaN         NaN
min       1.00000        NaN       NaN            NaN         NaN
25%       3.25000        NaN       NaN            NaN         NaN
50%       5.50000        NaN       NaN            NaN         NaN
75%       7.75000        NaN       NaN            NaN         NaN
max      10.00000        NaN       NaN            NaN         NaN

                     email  department_id  experience_years
count                   10      10.000000          10.00000
unique                  10            NaN               NaN
top     arjun@hospital.com            NaN               NaN
freq                     1            NaN               NaN
mean                   NaN       3.100000           8.50000
std                    NaN       1.595131           3.02765
min                    NaN       1.000000           4.00000
25%                    NaN       2.000000           6.25000
50%                    NaN       3.000000           8.50000
75%                    NaN       4.750000          10.75000
max                    NaN       5.000000          13.00000

📌 NumPy Statistics

experience_years
Mean: 8.5
Median: 8.5
Minimum: 4
Maximum: 13
Standard Deviation: 2.8722813232690143

📌 Frequency Analysis

specialization
specialization
Emergency       3
Cardiologist    2
Neurologist     2
Orthopedic      2
Pediatrician    1
Name: count, dtype: int64

======================================================================
======================================================================
EDA REPORT : PATIENTS
======================================================================

📌 Shape
(30, 10)

📌 Columns
['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'phone', 'email', 'address', 'blood_group', 'registration_date']

📌 Data Types
patient_id           int64
first_name             str
last_name              str
gender                 str
date_of_birth          str
phone                  str
email                  str
address                str
blood_group            str
registration_date      str
dtype: object

📌 Missing Values
patient_id           0
first_name           0
last_name            0
gender               0
date_of_birth        0
phone                0
email                0
address              0
blood_group          0
registration_date    0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        patient_id first_name last_name gender date_of_birth       phone  \
count    30.000000         30        30     30            30          30
unique         NaN         30         1      2            10          30
top            NaN   Patient1      Test   Male    1981-01-15  9800000001
freq           NaN          1        30     15             3           1
mean     15.500000        NaN       NaN    NaN           NaN         NaN
std       8.803408        NaN       NaN    NaN           NaN         NaN
min       1.000000        NaN       NaN    NaN           NaN         NaN
25%       8.250000        NaN       NaN    NaN           NaN         NaN
50%      15.500000        NaN       NaN    NaN           NaN         NaN
75%      22.750000        NaN       NaN    NaN           NaN         NaN
max      30.000000        NaN       NaN    NaN           NaN         NaN

                    email address blood_group registration_date
count                  30      30          30                30
unique                 30      30           1                28
top     patient1@mail.com  City 1          O+        2026-06-02
freq                    1       1          30                 2
mean                  NaN     NaN         NaN               NaN
std                   NaN     NaN         NaN               NaN
min                   NaN     NaN         NaN               NaN
25%                   NaN     NaN         NaN               NaN
50%                   NaN     NaN         NaN               NaN
75%                   NaN     NaN         NaN               NaN
max                   NaN     NaN         NaN               NaN

📌 Frequency Analysis

gender
gender
Male      15
Female    15
Name: count, dtype: int64

blood_group
blood_group
O+    30
Name: count, dtype: int64

======================================================================
======================================================================
EDA REPORT : DEPARTMENTS
======================================================================

📌 Shape
(5, 4)

📌 Columns
['department_id', 'department_name', 'location', 'head_of_department']

📌 Data Types
department_id          int64
department_name          str
location                 str
head_of_department    object
dtype: object

📌 Missing Values
department_id         0
department_name       0
location              0
head_of_department    5
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        department_id department_name           location head_of_department
count        5.000000               5                  5                  0
unique            NaN               5                  5                  0
top               NaN      Cardiology  Block A - Floor 2                NaN
freq              NaN               1                  1                NaN
mean         3.000000             NaN                NaN                NaN
std          1.581139             NaN                NaN                NaN
min          1.000000             NaN                NaN                NaN
25%          2.000000             NaN                NaN                NaN
50%          3.000000             NaN                NaN                NaN
75%          4.000000             NaN                NaN                NaN
max          5.000000             NaN                NaN                NaN

📌 Frequency Analysis

department_name
department_name
Cardiology     1
Neurology      1
Orthopedics    1
Pediatrics     1
Emergency      1
Name: count, dtype: int64

location
location
Block A - Floor 2    1
Block B - Floor 3    1
Block C - Floor 1    1
Block A - Floor 1    1
Ground Floor         1
Name: count, dtype: int64

======================================================================
======================================================================
EDA REPORT : APPOINTMENTS
======================================================================

📌 Shape
(50, 6)

📌 Columns
['appointment_id', 'patient_id', 'doctor_id', 'appointment_date', 'appointment_time', 'appointment_status']

📌 Data Types
appointment_id        int64
patient_id            int64
doctor_id             int64
appointment_date        str
appointment_time        str
appointment_status      str
dtype: object

📌 Missing Values
appointment_id        0
patient_id            0
doctor_id             0
appointment_date      0
appointment_time      0
appointment_status    0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        appointment_id  patient_id  doctor_id appointment_date  \
count         50.00000   50.000000  50.000000               50
unique             NaN         NaN        NaN               28
top                NaN         NaN        NaN       2026-07-01
freq               NaN         NaN        NaN                2
mean          25.50000   13.500000   5.500000              NaN
std           14.57738    8.096989   2.901442              NaN
min            1.00000    1.000000   1.000000              NaN
25%           13.25000    7.000000   3.000000              NaN
50%           25.50000   13.000000   5.500000              NaN
75%           37.75000   19.000000   8.000000              NaN
max           50.00000   30.000000  10.000000              NaN

       appointment_time appointment_status
count                50                 50
unique                1                  4
top               09:00          Completed
freq                 50                 35
mean                NaN                NaN
std                 NaN                NaN
min                 NaN                NaN
25%                 NaN                NaN
50%                 NaN                NaN
75%                 NaN                NaN
max                 NaN                NaN

📌 Frequency Analysis

appointment_status
appointment_status
Completed    35
Cancelled     5
No Show       5
Scheduled     5
Name: count, dtype: int64

======================================================================
======================================================================
EDA REPORT : ENCOUNTERS
======================================================================

📌 Shape
(35, 5)

📌 Columns
['encounter_id', 'appointment_id', 'diagnosis', 'consultation_notes', 'consultation_duration']

📌 Data Types
encounter_id             int64
appointment_id           int64
diagnosis                  str
consultation_notes         str
consultation_duration    int64
dtype: object

📌 Missing Values
encounter_id             0
appointment_id           0
diagnosis                0
consultation_notes       0
consultation_duration    0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        encounter_id  appointment_id    diagnosis consultation_notes  \
count      35.000000       35.000000           35                 35
unique           NaN             NaN           35                  1
top              NaN             NaN  Diagnosis 1             Stable
freq             NaN             NaN            1                 35
mean       18.000000       18.000000          NaN                NaN
std        10.246951       10.246951          NaN                NaN
min         1.000000        1.000000          NaN                NaN
25%         9.500000        9.500000          NaN                NaN
50%        18.000000       18.000000          NaN                NaN
75%        26.500000       26.500000          NaN                NaN
max        35.000000       35.000000          NaN                NaN

        consultation_duration
count               35.000000
unique                    NaN
top                       NaN
freq                      NaN
mean                21.428571
std                  4.333764
min                 15.000000
25%                 18.000000
50%                 21.000000
75%                 25.000000
max                 29.000000

📌 NumPy Statistics

consultation_duration
Mean: 21.428571428571427
Median: 21.0
Minimum: 15
Maximum: 29
Standard Deviation: 4.271404682207444

======================================================================
======================================================================
EDA REPORT : BILLING
======================================================================

📌 Shape
(35, 4)

📌 Columns
['bill_id', 'encounter_id', 'total_amount', 'billing_date']

📌 Data Types
bill_id         int64
encounter_id    int64
total_amount    int64
billing_date      str
dtype: object

📌 Missing Values
bill_id         0
encounter_id    0
total_amount    0
billing_date    0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
          bill_id  encounter_id  total_amount billing_date
count   35.000000     35.000000     35.000000           35
unique        NaN           NaN           NaN           28
top           NaN           NaN           NaN   2026-07-01
freq          NaN           NaN           NaN            2
mean    18.000000     18.000000   4000.000000          NaN
std     10.246951     10.246951   1434.860108          NaN
min      1.000000      1.000000   2000.000000          NaN
25%      9.500000      9.500000   3000.000000          NaN
50%     18.000000     18.000000   4000.000000          NaN
75%     26.500000     26.500000   5000.000000          NaN
max     35.000000     35.000000   6000.000000          NaN

📌 NumPy Statistics

total_amount
Mean: 4000.0
Median: 4000.0
Minimum: 2000
Maximum: 6000
Standard Deviation: 1414.213562373095

======================================================================
======================================================================
EDA REPORT : PAYMENTS
======================================================================

📌 Shape
(35, 6)

📌 Columns
['payment_id', 'bill_id', 'payment_method', 'payment_status', 'payment_date', 'amount_paid']

📌 Data Types
payment_id        int64
bill_id           int64
payment_method      str
payment_status      str
payment_date        str
amount_paid       int64
dtype: object

📌 Missing Values
payment_id        0
bill_id           0
payment_method    0
payment_status    0
payment_date      0
amount_paid       0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        payment_id    bill_id payment_method payment_status payment_date  \
count    35.000000  35.000000             35             35           35
unique         NaN        NaN              4              2           28
top            NaN        NaN           Cash           Paid   2026-07-01
freq           NaN        NaN              9             32            2
mean     18.000000  18.000000            NaN            NaN          NaN
std      10.246951  10.246951            NaN            NaN          NaN
min       1.000000   1.000000            NaN            NaN          NaN
25%       9.500000   9.500000            NaN            NaN          NaN
50%      18.000000  18.000000            NaN            NaN          NaN
75%      26.500000  26.500000            NaN            NaN          NaN
max      35.000000  35.000000            NaN            NaN          NaN

        amount_paid
count     35.000000
unique          NaN
top             NaN
freq            NaN
mean    3828.571429
std     1757.098449
min        0.000000
25%     3000.000000
50%     4000.000000
75%     5000.000000
max     6000.000000

📌 NumPy Statistics

amount_paid
Mean: 3828.5714285714284
Median: 4000.0
Minimum: 0
Maximum: 6000
Standard Deviation: 1731.81513836477

📌 Frequency Analysis

payment_method
payment_method
Cash         9
Card         9
Insurance    9
UPI          8
Name: count, dtype: int64

payment_status
payment_status
Paid       32
Pending     3
Name: count, dtype: int64

======================================================================
======================================================================
EDA REPORT : PRESCRIPTIONS
======================================================================

📌 Shape
(60, 5)

📌 Columns
['prescription_id', 'encounter_id', 'medicine_name', 'dosage', 'duration_days']

📌 Data Types
prescription_id    int64
encounter_id       int64
medicine_name        str
dosage               str
duration_days      int64
dtype: object

📌 Missing Values
prescription_id    0
encounter_id       0
medicine_name      0
dosage             0
duration_days      0
dtype: int64

📌 Duplicate Rows
0

📌 Summary Statistics
        prescription_id  encounter_id medicine_name                dosage  \
count         60.000000     60.000000            60                    60
unique              NaN           NaN            60                     1
top                 NaN           NaN    Medicine 1  1 tablet twice daily
freq                NaN           NaN             1                    60
mean          30.500000     15.916667           NaN                   NaN
std           17.464249      9.419222           NaN                   NaN
min            1.000000      1.000000           NaN                   NaN
25%           15.750000      8.000000           NaN                   NaN
50%           30.500000     15.500000           NaN                   NaN
75%           45.250000     23.000000           NaN                   NaN
max           60.000000     35.000000           NaN                   NaN

        duration_days
count            60.0
unique            NaN
top               NaN
freq              NaN
mean              7.0
std               0.0
min               7.0
25%               7.0
50%               7.0
75%               7.0
max               7.0

📌 NumPy Statistics

duration_days
Mean: 7.0
Median: 7.0
Minimum: 7
Maximum: 7
Standard Deviation: 0.0

📌 Frequency Analysis

medicine_name
medicine_name
Medicine 1     1
Medicine 2     1
Medicine 3     1
Medicine 4     1
Medicine 5     1
Medicine 6     1
Medicine 7     1
Medicine 8     1
Medicine 9     1
Medicine 10    1
Medicine 11    1
Medicine 12    1
Medicine 13    1
Medicine 14    1
Medicine 15    1
Medicine 16    1
Medicine 17    1
Medicine 18    1
Medicine 19    1
Medicine 20    1
Medicine 21    1
Medicine 22    1
Medicine 23    1
Medicine 24    1
Medicine 25    1
Medicine 26    1
Medicine 27    1
Medicine 28    1
Medicine 29    1
Medicine 30    1
Medicine 31    1
Medicine 32    1
Medicine 33    1
Medicine 34    1
Medicine 35    1
Medicine 36    1
Medicine 37    1
Medicine 38    1
Medicine 39    1
Medicine 40    1
Medicine 41    1
Medicine 42    1
Medicine 43    1
Medicine 44    1
Medicine 45    1
Medicine 46    1
Medicine 47    1
Medicine 48    1
Medicine 49    1
Medicine 50    1
Medicine 51    1
Medicine 52    1
Medicine 53    1
Medicine 54    1
Medicine 55    1
Medicine 56    1
Medicine 57    1
Medicine 58    1
Medicine 59    1
Medicine 60    1
Name: count, dtype: int64

======================================================================

In [9]:
####Patient_Analysis:
import sqlite3

connection = sqlite3.connect(
    "/Users/akshitajoshi/Hospital_Data_Analytics_Internship/Hospital-Operations-Analytics.db"
)
import pandas as pd
import numpy as np

patients_df = pd.read_sql_query(
    "SELECT * FROM Patients;",
    connection
)
appointments_df = pd.read_sql_query("SELECT * FROM appointments;", connection)


print("Total Patients: " , patients_df["patient_id"].nunique())
gender_counts = patients_df["gender"].value_counts()
print(gender_counts)

patient_visits = (
    appointments_df
    .groupby("patient_id")
    .size()
    .reset_index(name="total_appointments")
)
patient_visits



patient_visits.sort_values(
    by="total_appointments",
    ascending=False
).head(10)




top_patients = patient_visits.merge(
    patients_df[
        ["patient_id", "first_name", "last_name"]
    ],
    on="patient_id"
)

top_patients.sort_values(
    by="total_appointments",
    ascending=False
).head(10)

Total Patients:  30
gender
Male      15
Female    15
Name: count, dtype: int64

    patient_id  total_appointments first_name last_name
0            1                   2   Patient1      Test
11          12                   2  Patient12      Test
19          20                   2  Patient20      Test
18          19                   2  Patient19      Test
17          18                   2  Patient18      Test
16          17                   2  Patient17      Test
1            2                   2   Patient2      Test
14          15                   2  Patient15      Test
13          14                   2  Patient14      Test
12          13                   2  Patient13      Test