In [1]:
import sqlite3

connection = sqlite3.connect(
    "/Users/akshitajoshi/Hospital_Data_Analytics_Internship/Hospital-Operations-Analytics.db"
)
import pandas as pd
import numpy as np

In [2]:
patients_df = pd.read_sql_query("SELECT * FROM patients;", connection)

doctors_df = pd.read_sql_query("SELECT * FROM doctors;", connection)

departments_df = pd.read_sql_query("SELECT * FROM departments;", connection)

appointments_df = pd.read_sql_query("SELECT * FROM appointments;", connection)

encounters_df = pd.read_sql_query("SELECT * FROM encounters;", connection)

billing_df = pd.read_sql_query("SELECT * FROM billing;", connection)

payments_df = pd.read_sql_query("SELECT * FROM payments;", connection)

prescriptions_df = pd.read_sql_query("SELECT * FROM prescriptions;", connection)

In [3]:
dashboard_df = appointments_df.merge(
    patients_df[
        [
            "patient_id",
            "first_name",
            "last_name",
            "gender",
            "blood_group",
            "registration_date"
        ]
    ],
    on="patient_id",
    how="left"
)

dashboard_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_status,first_name,last_name,gender,blood_group,registration_date
0,1,1,1,2026-07-01,09:00,Completed,Patient1,Test,Male,O+,2026-06-02
1,2,2,2,2026-07-02,09:00,Completed,Patient2,Test,Female,O+,2026-06-03
2,3,3,3,2026-07-03,09:00,Completed,Patient3,Test,Male,O+,2026-06-04
3,4,4,4,2026-07-04,09:00,Completed,Patient4,Test,Female,O+,2026-06-05
4,5,5,5,2026-07-05,09:00,Completed,Patient5,Test,Male,O+,2026-06-06

In [4]:
dashboard_df = dashboard_df.merge(
    doctors_df[
        [
            "doctor_id",
            "first_name",
            "last_name",
            "specialization",
            "department_id"
        ]
    ],
    on="doctor_id",
    how="left",
    suffixes=("_patient", "_doctor")
)

dashboard_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_status,first_name_patient,last_name_patient,gender,blood_group,registration_date,first_name_doctor,last_name_doctor,specialization,department_id
0,1,1,1,2026-07-01,09:00,Completed,Patient1,Test,Male,O+,2026-06-02,Arjun,Mehta,Cardiologist,1
1,2,2,2,2026-07-02,09:00,Completed,Patient2,Test,Female,O+,2026-06-03,Neha,Kapoor,Cardiologist,1
2,3,3,3,2026-07-03,09:00,Completed,Patient3,Test,Male,O+,2026-06-04,Rohan,Iyer,Neurologist,2
3,4,4,4,2026-07-04,09:00,Completed,Patient4,Test,Female,O+,2026-06-05,Priya,Nair,Neurologist,2
4,5,5,5,2026-07-05,09:00,Completed,Patient5,Test,Male,O+,2026-06-06,Vikram,Singh,Orthopedic,3

In [5]:
dashboard_df = dashboard_df.merge(
    departments_df[
        [
            "department_id",
            "department_name"
        ]
    ],
    on="department_id",
    how="left"
)

dashboard_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_status,first_name_patient,last_name_patient,gender,blood_group,registration_date,first_name_doctor,last_name_doctor,specialization,department_id,department_name
0,1,1,1,2026-07-01,09:00,Completed,Patient1,Test,Male,O+,2026-06-02,Arjun,Mehta,Cardiologist,1,Cardiology
1,2,2,2,2026-07-02,09:00,Completed,Patient2,Test,Female,O+,2026-06-03,Neha,Kapoor,Cardiologist,1,Cardiology
2,3,3,3,2026-07-03,09:00,Completed,Patient3,Test,Male,O+,2026-06-04,Rohan,Iyer,Neurologist,2,Neurology
3,4,4,4,2026-07-04,09:00,Completed,Patient4,Test,Female,O+,2026-06-05,Priya,Nair,Neurologist,2,Neurology
4,5,5,5,2026-07-05,09:00,Completed,Patient5,Test,Male,O+,2026-06-06,Vikram,Singh,Orthopedic,3,Orthopedics

In [6]:
dashboard_df = dashboard_df.merge(
    encounters_df[
        [
            "encounter_id",
            "appointment_id",
            "diagnosis",
            "consultation_duration"
        ]
    ],
    on="appointment_id",
    how="left"
)

dashboard_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_status,first_name_patient,last_name_patient,gender,blood_group,registration_date,first_name_doctor,last_name_doctor,specialization,department_id,department_name,encounter_id,diagnosis,consultation_duration
0,1,1,1,2026-07-01,09:00,Completed,Patient1,Test,Male,O+,2026-06-02,Arjun,Mehta,Cardiologist,1,Cardiology,1.0,Diagnosis 1,16.0
1,2,2,2,2026-07-02,09:00,Completed,Patient2,Test,Female,O+,2026-06-03,Neha,Kapoor,Cardiologist,1,Cardiology,2.0,Diagnosis 2,17.0
2,3,3,3,2026-07-03,09:00,Completed,Patient3,Test,Male,O+,2026-06-04,Rohan,Iyer,Neurologist,2,Neurology,3.0,Diagnosis 3,18.0
3,4,4,4,2026-07-04,09:00,Completed,Patient4,Test,Female,O+,2026-06-05,Priya,Nair,Neurologist,2,Neurology,4.0,Diagnosis 4,19.0
4,5,5,5,2026-07-05,09:00,Completed,Patient5,Test,Male,O+,2026-06-06,Vikram,Singh,Orthopedic,3,Orthopedics,5.0,Diagnosis 5,20.0

In [7]:
dashboard_df = dashboard_df.merge(
    billing_df[
        [
            "bill_id",
            "encounter_id",
            "total_amount"
        ]
    ],
    on="encounter_id",
    how="left"
)

dashboard_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_status,first_name_patient,last_name_patient,gender,blood_group,...,first_name_doctor,last_name_doctor,specialization,department_id,department_name,encounter_id,diagnosis,consultation_duration,bill_id,total_amount
0,1,1,1,2026-07-01,09:00,Completed,Patient1,Test,Male,O+,...,Arjun,Mehta,Cardiologist,1,Cardiology,1.0,Diagnosis 1,16.0,1.0,3000.0
1,2,2,2,2026-07-02,09:00,Completed,Patient2,Test,Female,O+,...,Neha,Kapoor,Cardiologist,1,Cardiology,2.0,Diagnosis 2,17.0,2.0,4000.0
2,3,3,3,2026-07-03,09:00,Completed,Patient3,Test,Male,O+,...,Rohan,Iyer,Neurologist,2,Neurology,3.0,Diagnosis 3,18.0,3.0,5000.0
3,4,4,4,2026-07-04,09:00,Completed,Patient4,Test,Female,O+,...,Priya,Nair,Neurologist,2,Neurology,4.0,Diagnosis 4,19.0,4.0,6000.0
4,5,5,5,2026-07-05,09:00,Completed,Patient5,Test,Male,O+,...,Vikram,Singh,Orthopedic,3,Orthopedics,5.0,Diagnosis 5,20.0,5.0,2000.0

In [8]:
dashboard_df = dashboard_df.merge(
    payments_df[
        [
            "bill_id",
            "payment_status",
            "payment_method",
            "amount_paid"
        ]
    ],
    on="bill_id",
    how="left"
)

dashboard_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_status,first_name_patient,last_name_patient,gender,blood_group,...,department_id,department_name,encounter_id,diagnosis,consultation_duration,bill_id,total_amount,payment_status,payment_method,amount_paid
0,1,1,1,2026-07-01,09:00,Completed,Patient1,Test,Male,O+,...,1,Cardiology,1.0,Diagnosis 1,16.0,1.0,3000.0,Paid,Cash,3000.0
1,2,2,2,2026-07-02,09:00,Completed,Patient2,Test,Female,O+,...,1,Cardiology,2.0,Diagnosis 2,17.0,2.0,4000.0,Paid,Card,4000.0
2,3,3,3,2026-07-03,09:00,Completed,Patient3,Test,Male,O+,...,2,Neurology,3.0,Diagnosis 3,18.0,3.0,5000.0,Paid,Insurance,5000.0
3,4,4,4,2026-07-04,09:00,Completed,Patient4,Test,Female,O+,...,2,Neurology,4.0,Diagnosis 4,19.0,4.0,6000.0,Paid,UPI,6000.0
4,5,5,5,2026-07-05,09:00,Completed,Patient5,Test,Male,O+,...,3,Orthopedics,5.0,Diagnosis 5,20.0,5.0,2000.0,Paid,Cash,2000.0

In [9]:
dashboard_df["Patient Name"] = (
    dashboard_df["first_name_patient"] +
    " " +
    dashboard_df["last_name_patient"]
)

dashboard_df["Doctor Name"] = (
    dashboard_df["first_name_doctor"] +
    " " +
    dashboard_df["last_name_doctor"]
)

In [10]:
dashboard_df = dashboard_df[
    [
        "appointment_id",
        "Patient Name",
        "gender",
        "blood_group",
        "registration_date",
        "Doctor Name",
        "specialization",
        "department_name",
        "appointment_status",
        "diagnosis",
        "consultation_duration",
        "total_amount",
        "amount_paid",
        "payment_status",
        "payment_method"
    ]
]

dashboard_df.head()

,appointment_id,Patient Name,gender,blood_group,registration_date,Doctor Name,specialization,department_name,appointment_status,diagnosis,consultation_duration,total_amount,amount_paid,payment_status,payment_method
0,1,Patient1 Test,Male,O+,2026-06-02,Arjun Mehta,Cardiologist,Cardiology,Completed,Diagnosis 1,16.0,3000.0,3000.0,Paid,Cash
1,2,Patient2 Test,Female,O+,2026-06-03,Neha Kapoor,Cardiologist,Cardiology,Completed,Diagnosis 2,17.0,4000.0,4000.0,Paid,Card
2,3,Patient3 Test,Male,O+,2026-06-04,Rohan Iyer,Neurologist,Neurology,Completed,Diagnosis 3,18.0,5000.0,5000.0,Paid,Insurance
3,4,Patient4 Test,Female,O+,2026-06-05,Priya Nair,Neurologist,Neurology,Completed,Diagnosis 4,19.0,6000.0,6000.0,Paid,UPI
4,5,Patient5 Test,Male,O+,2026-06-06,Vikram Singh,Orthopedic,Orthopedics,Completed,Diagnosis 5,20.0,2000.0,2000.0,Paid,Cash

In [11]:
dashboard_df.to_csv(
    "hospital_dashboard_data.csv",
    index=False
)

print("Dashboard dataset created successfully!")

Dashboard dataset created successfully!

In [12]:
dashboard_df.shape

(50, 15)

In [13]:
dashboard_df.head()

,appointment_id,Patient Name,gender,blood_group,registration_date,Doctor Name,specialization,department_name,appointment_status,diagnosis,consultation_duration,total_amount,amount_paid,payment_status,payment_method
0,1,Patient1 Test,Male,O+,2026-06-02,Arjun Mehta,Cardiologist,Cardiology,Completed,Diagnosis 1,16.0,3000.0,3000.0,Paid,Cash
1,2,Patient2 Test,Female,O+,2026-06-03,Neha Kapoor,Cardiologist,Cardiology,Completed,Diagnosis 2,17.0,4000.0,4000.0,Paid,Card
2,3,Patient3 Test,Male,O+,2026-06-04,Rohan Iyer,Neurologist,Neurology,Completed,Diagnosis 3,18.0,5000.0,5000.0,Paid,Insurance
3,4,Patient4 Test,Female,O+,2026-06-05,Priya Nair,Neurologist,Neurology,Completed,Diagnosis 4,19.0,6000.0,6000.0,Paid,UPI
4,5,Patient5 Test,Male,O+,2026-06-06,Vikram Singh,Orthopedic,Orthopedics,Completed,Diagnosis 5,20.0,2000.0,2000.0,Paid,Cash

In [15]:
import os

print(os.getcwd())

/Users/akshitajoshi